# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


Movie.create(title:"The Karate Kid", rating: "PG")
Movie.create(title:"Batman Forever", rating: "PG")
Movie.create(title:"Avengers", rating: "PG")
Movie.create(title:"Friday the 13th", rating: "R")
Movie.create(title:"Elf", rating: "PG")
Movie.create(title:"Mulan", rating: "PG")
Movie.create(title:"Lilo and Stitch", rating: "PG")
Movie.create(title:"The Longest Yard", rating: "PG13")
Movie.create(title:"Pokemon", rating: "PG")
Movie.create(title:"Matilda", rating: "PG") 
Movie.create(title:"Wonder Woman",  rating: "PG")
Movie.create(title:"Inception", rating: "PG13")
Movie.create(title:"Lion King", rating: "PG") 
Movie.create(title:"Toy Story", rating: "PG") 
Movie.create(title:"Aladdin", rating: "PG")
Movie.create(title:"Nightmare on Elm Street", rating: "R")
Movie.create(title:"Halloween", rating: "R")
Movie.create(title:"Nightmare Before Christmas", rating: "PG")
Movie.create(title:"Pokemon 2000", rating: "PG")
Movie.create(title:"Cinderella", rating: "PG")
Movie.create(title:"IronMan", rating: "PG13")
Movie.create(title:"Man of Steel", rating: "PG13")
Movie.create(title:"Batman and Robin", rating: "PG13")
Movie.create(title:"Fox and the Hound", rating: "PG")
Movie.create(title:"Lion King", rating: "PG")
Movie.create(title:"Lego Movie", rating: "PG")
Movie.create(title:"Glass", rating: "R")
Movie.create(title:"Split", rating: "R")
Movie.create(title:"Die Hard", rating: "R")
Movie.create(title:"Back to the Future", rating: "PG13")
Movie.create(title:"Happy Gilmore", rating: "PG13")
Movie.create(title:"Mr. Deeds", rating: "PG13")
Movie.create(title:"Mars Attacks", rating: "R")
Movie.create(title:"Independence Day", rating: "PG13")
Movie.create(title:"Beauty and the Beast", rating: "PG")
